#!/usr/bin/env node

var program = require('commander');
var mongoose = require('mongoose');
var inquirer = require('inquirer');
var colors = require('colors');
var slug = require('slug');
var tokenUtil = require('../lib/utils/token');
var pkg = require('../package');
var settings = require('../settings');

program
  .version(pkg.version)
  .option('-a, --app [name]', 'App Name (will be slugified)')
  .option('-n, --name [author]', 'Name of author requesting token')
  .option('-e, --email [address]', 'Email of author requesting token')
  .option('-d, --text [description]', 'Short description of app')
  .parse(process.argv);

//the logo
var logo = "\n\
                                                                            \n\
           0xxxx00                                                          \n\
             00xxxx0    00                                        00        \n\
                0x0 0000000000                                 0xxxx0       \n\
       0        00 000000000000  0000000000000000000000000  0xxx00          \n\
       0xx00   0x 00000000000000 0000000000000000000000000 xx0              \n\
        0xxxxxxxx  0000000000000 0000000000000000000000000                  \n\
          000xx000 000000000000                 0000000000                  \n\
                      000000   xxx00         000 00000000                   \n\
                      0    000 xxxxxxx00  0xxx0  00000000                   \n\
                      00000000 xxxxxxxxxx000     0000000                    \n\
                       0000000  0xxxxxxxxxxxx0  0000000                     \n\
                        0000000 0x000xxxxxxxxx 0000000                      \n\
                      00 0000000 0x   000xxxx 0000000                       \n\
                  00xxxxx  000000         00 0000000 0x000  0000            \n\
               0xxxxxxxxxx0 0000  0        0000000 0xxxxxxxxxxxxxx0         \n\
           0xxxxxxxxxxxxxx00    00000    0000000  0xxxxxxxxxx0 00xxx        \n\
        0x00xxxxxxxxxxx0         0000000000000       00xxxx0       00       \n\
        0xx00xxxxxx00              00000000            0xxx                 \n\
          xx00xx0                     00                xxxx00              \n\
           00                                            00xxxxx0           \n\
                                                                            \n\
 ________  ________  _______   ________         ___  ___  ___  ________     \n\
|\\   __  \\|\\   __  \\|\\  ___ \\ |\\   ___  \\      |\\  \\|\\  \\|\\  \\|\\   __  \\    \n\
\\ \\  \\|\\  \\ \\  \\|\\  \\ \\   __/|\\ \\  \\\\ \\  \\     \\ \\  \\ \\  \\\\\\  \\ \\  \\|\\ /_   \n\
 \\ \\  \\\\\\  \\ \\   ____\\ \\  \\_|/_\\ \\  \\\\ \\  \\  __ \\ \\  \\ \\  \\\\\\  \\ \\   __  \\  \n\
  \\ \\  \\\\\\  \\ \\  \\___|\\ \\  \\_|\\ \\ \\  \\\\ \\  \\|\\  \\\\_\\  \\ \\  \\\\\\  \\ \\  \\|\\  \\ \n\
   \\ \\_______\\ \\__\\    \\ \\_______\\ \\__\\\\ \\__\\ \\________\\ \\_______\\ \\_______\\\n\
    \\|_______|\\|__|     \\|_______|\\|__| \\|__|\\|________|\\|_______|\\|_______|\n\
                                                                            ";

console.log(logo.cyan);

console.log('Generate Developer Access Token'.bold);

var questions = [];

if (!program.app) {
  questions.push({
    type: 'input',
    name: 'app',
    message: 'Name of Application (will be slugified):',
    validate: function (value) {
      var pass = value.length !== 0;
      if (pass) {
        return true;
      } else {
        return 'Please Enter an Application Name'
      }
    }
  });
}

if (!program.name) {
  questions.push({
    type: 'input',
    name: 'name',
    message: 'Name of Author Requesting Token:',
    validate: function (value) {
      var pass = value.length !== 0;
      if (pass) {
        return true;
      } else {
        return 'Please Enter an Author'
      }
    }
  });
}

if (program.email && program.email.indexOf('@jacobs-university.de') === -1) {
  delete program.email;
}

if (!program.email) {
  questions.push({
    type: 'input',
    name: 'email',
    message: 'Email of Author Requesting Token:',
    validate: function (value) {
      if (value.indexOf('@jacobs-university.de') === -1) {
        return 'Please Enter a Valid Jacobs University Email'
      } else {
        return true;
      }
    }
  });
}

if (!program.text) {
  questions.push({
    type: 'input',
    name: 'description',
    message: 'Short Description of Application:'
  });
}

inquirer.prompt(questions, function (answers) {
  var info = {};
  info.app = program.app || answers.app;
  info.name = program.name || answers.name;
  info.email = program.email || answers.email;
  info.description = program.text || answers.description;

  info.app = slug(info.app);

  console.log('INFO '.cyan + 'Generate Token');
  var token = tokenUtil.generateDeveloper(info);
  if (token === null) {
    console.log('ERR '.red + 'Something went wrong');
  }
  console.log('OK '.green + 'Token generated');
  console.log('---------------------------');
  console.log('app-name: '.cyan + info.app);
  console.log('token: '.cyan + token);
});
