#!/usr/bin/env node

var program = require('commander');
var mongoose = require('mongoose');
var colors = require('colors');
var ldapjs = require('ldapjs');
var prompt = require('prompt');
var inquirer = require('inquirer');
var ldap = ldapjs.createClient({url:'ldap://jacobs.jacobs-university.de'});
var modelImport = require('../lib/models');
var pkg = require('../package');
var settings = require('../settings');
var mapping = require('../room/data/mapping');

mongoose.connect(settings.database);
Models = modelImport(mongoose);

var done = 0; //keep a counter of what we have finished

for (var i = 0; i < mapping.length; i++) {
  if (mapping[i].phone && mapping[i].room) {
    var m = new Models.PhoneRoom(mapping[i]);
    console.log('model', m);
    m.save(function(err) {
      if (err) {
        console.log(err);
      } else {
        done++;
        if(done == mapping.length){ //we have now finished saving everything,
          process.exit(0); //so we can exit
        }
      }
    });
  }
}
return;
